name:    hls-simple
version: 0.1.0.0
license: BSD3
author: "sgal"
copyright: "2018 sgal"

default-extensions:
- GADTs
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell
- ViewPatterns

extra-source-files:
- README.md

description: See package README for details.

dependencies:
- base >= 4.8.2.0 && < 4.9 || >= 4.9.1.0 && < 5
- bytestring >= 0.9 && < 0.11
- directory >= 1.1 && < 1.4
- regex-pcre-builtin >= 0.94 && < 1
- time
- warp
- yesod >= 1.6 && < 1.7
- yesod-core >= 1.6 && < 1.7
- yesod-static >= 1.6 && < 1.7

library:
  source-dirs: lib
  ghc-options:
  - -O
  - -Wall
  - -Werror

# Runnable executable for our application
executables:
  hls-simple:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O
    - -Wall
    - -Werror
    dependencies:
    - hls-simple
